language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - coverage run --source PyDB -m py.test

after_success:
  - coveralls
